### PR TITLE
Some suggestions

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Use a type for the relationship and use QueryProxy chaining to make code a bit cleaner

Don't have time to test it at the moment, but this should work and should be a bit cleaner

### CODE REVIEW

**Comment by chrislgrigg** [comment]
If you upgrade to 3.0.4, you'll get the `find_or_create_by` method, too!

Also, you guys should be aware that v3 of the gem is not compatible with Neo4j 2.2. We released a new stable RC of v4 yesterday, `~> 4.0.0.rc.3`.

**Comment by dpritchett** [comment]
Thanks y'all!  I'll have to figure out how a branching scheme to take new code without invalidating the blog content since I don't necessarily have the ability to edit it easily.

**Comment by jeremykendall** [comment]
> I'll have to figure out how a branching scheme to take new code without invalidating the blog content

Here's what I do:
- Create a release for the version covered by the blog post
- Create a develop branch
- Request all PRs be made from feature branches against the develop branch.

If you add a CONTRIBUTING.md file to the root of the repo ([here's an example](https://github.com/GraphStory/graph-kit-php/blob/develop/CONTRIBUTING.md) from the Graph Kit for PHP), the guidelines you add there will be shared with contributors when they open a PR.

**Comment by dpritchett** [comment]
I decided to just `git tag` the original blog release and then take PRs as they come.  Thanks everyone!

**Comment by chrislgrigg** [comment]
Where is the `product` identifier in this query defined?

```
users.purchases(:other_product).where("other_product.slug <> product.slug").
         limit(limit).
         pluck('DISTINCT other_product')
```

**Comment by dpritchett** [comment]
Good question, @cheerfulstoic did we miss a step?

**Comment by chrislgrigg** [comment]
It was a loaded question... you did. ;-) Brian mentioned to me that he wrote it up really fast originally. This should do it for you.

``` ruby
users.purchases(:product).users.products(:other_product)
  .where("other_product.slug <> product.slug")
  .limit(limit)
  .pluck('DISTINCT other_product')
```

Haven't tested this in your code, but just eyeballing it, it looks right.

Your performance will be a lot better, too. It'll be more than 2x faster than that if you switch to the master branch of neo4j and neo4j-core, too, but it might require some reworking of other code.

**Pull request merged**
