### PR TITLE
Fix users_also_bought query

### PR DESCRIPTION
**Pull request by kitwalker12**

### CODE REVIEW

**Comment by dpritchett** [comment]
Nice!  This has been changed via PRs a few times already but I don't know that any of us actually ran it after the initial pure-cypher version.  How did you end up here?

**Comment by kitwalker12** [comment]
@dpritchett I was trying to implement it in our spree store on [our website](http://www.violetgrey.com/) using the latest version of this code and neo4j kept raising exceptions with the error `NoMethodError: undefined method `products' for #<Neo4j::ActiveNode::Query::QueryProxy>`

**Comment by chrislgrigg** [comment]
@kitwalker12  is right, my edit that used `purchases` (I think that was mine, anyway?) was wrong. I eyeballed it and wrote it up, used the wrong association name -- sorry!

**Comment by dpritchett** [comment]
Ah, thanks!  I can vouch for the tagged https://github.com/GraphStory/graph-kit-ruby/tree/blog-post-final commit working; master has taken a few PRs in hopes of getting closer to idiomatic `neo4j` gem usage.

Thanks for pushing through the bug and getting it sorted @kitwalker12 :+1:

**Comment by chrislgrigg** [comment]
@dpritchett RE idiomatic `neo4j` gem usage, let me know if you want me to check out anything. If you want to plug our recent 4.1.0 release, that'd be suuuuper sweet, too! ;-) http://neo4jrb.io/blog/2015/01/09/neo4j-rb_v4-1_released.html

**Pull request merged**
